### ISSUE TITLE
Funding tab on governance page/row can't be removed

### ISSUE THREAD

**Issue by JamesAppletonDCVC** [VolunteerDublinCity/Dublin-City-Website#32]
# Bug
Funding tab on governance page/row can't be removed.

## Current result and How to recreate
There was a category of staff type called 'Funding'. This was deleted as there is now nothing in it and we don't want it to appear on the website. However, currently there is a button within the 'Governance' row type called 'Funding' which cannot be removed, so it is still visible on the Governance page.

## Expected Result
This 'Funding' button should be removed.

## Picture
![image](https://user-images.githubusercontent.com/38209254/38490650-8ff4a95c-3be1-11e8-98c0-5a3f4fd1e4ed.png)
![image](https://user-images.githubusercontent.com/38209254/38490681-a087ab5c-3be1-11e8-9fd2-d5d58e8f8966.png)
![image](https://user-images.githubusercontent.com/38209254/38490901-47f90d90-3be2-11e8-87a1-4ba199827b2b.png)

## Environment 
Windows 7 Professional
Google Chrome 65.0.3325.18

## URL
http://volunteerdublincity.ie/about-us/governence/

**Comment by Duncan-Mckenna** [comment]
Thanks for that James. I'll take a look at that today.

**Comment by Duncan-Mckenna** [comment]
Hey James, that should be fixed now. I'm going to close this one off.

**Comment by JamesAppletonDCVC** [comment]
Fix confirmed. Thanks Duncan!
