### ISSUE TITLE
JS Error: wb_full_bg_img is not defined

### ISSUE THREAD

**Issue by alfonsomartinde** [VolunteerDublinCity/Dublin-City-Website#9]
There's an error in some templates:

<img width="450" alt="wb_full_bg_img is not defined" src="https://cloud.githubusercontent.com/assets/1211800/24578691/c7164c0a-16e5-11e7-9894-a46af382a975.png">

The wb_full_bg_img declaration is commented out. Should be uncommented.

```javascript
	// Full Back Ground Images
	// function wb_full_bg_img(selector) {
	// 	var $selector = jQuery(''+selector+'');
	// 	var $img = $selector.attr('data-img');
	// 	if ($selector[0]) {
	// 		$selector.backstretch($img);
	// 	}
	// }
```

Also, there are some elements in the DOM that needs data-img attribute to make that function work again:

```javascript
	// Full Backgrounds
	wb_full_bg_img('.home');
	wb_full_bg_img('#vol-home');
	wb_full_bg_img('#org-home');
	wb_full_bg_img('.bottom-bg');
```

For instance, looking at #org-home element, we will need to change:

```php
<header id="org-home"
  style="background-size:cover;background-image:url(
    '<?php echo ( !empty($bg_img) ? $bg_img : $bg_img_bkup['url']);?>'
  )">
```

to

```php
<header id="org-home" 
  style="background-size:cover;background-image:url(
    '<?php echo ( !empty($bg_img) ? $bg_img : $bg_img_bkup['url']);?>'
  )" 
  data-img="<?php echo ( !empty($bg_img) ? $bg_img : $bg_img_bkup['url']);?>">
```

**Comment by Duncan-Mckenna** [comment]
All that JS function does is add two inline styles to the element: background-image: blah and background-size: cover. 

So as the image is already set in the template, it's probably better to just those two function calls themselves, for  #vol-home and #org-home

**Comment by alfonsomartinde** [comment]
After looking a bit closer at the code, I saw that _wb_full_bg_img_ function is using this jquery plugin: http://www.jquery-backstretch.com/ just for displaying background images as a slideshow.

Also the _wb_slick_fullbg_ function applies another plugin: http://kenwheeler.github.io/slick/ to the parent elements (first argument of _wb_slick_fullbg_), and Backstretch plugin to child ones (second argument).

So I think we are defining background-image: blah and background-size: cover in the templates as a fallback, and then the idea was having a slideshow as background images. I may be wrong, what do you think?

Maybe just adding an array of images will do the trick

```javascript
	function wb_full_bg_img(selector) {
		var $selector = jQuery(''+selector+'');
		var $img = $selector.attr('data-img');
		var bgImages = [];
		var i;

		if ($img) {
			bgImages = $img.split(',');
		}

		for(i=0;i<bgImages.length;i++){
			if (bgImages[i].trim() === '') {
				bgImages.splice(i, 1);
			}
		}

		if ($selector[0] && bgImages.length > 0) {
			console.log(bgImages);
			$selector.backstretch(bgImages, {duration: 3000, fade: 750});
		}
	}

wb_full_bg_img('.home');
```

and then 

```html
<body class="home bck_img" 
  style="background-image:url(<?php echo $bg_img['url'] ?>)"
  data-img="<?php ARRAY OF IMAGES ?>" 
  <?php body_class('animated fadeIn'); ?>>
```

See it in action:

![backstrech-example](https://cloud.githubusercontent.com/assets/1211800/25295663/c42a6f76-26e4-11e7-85e9-ede9b0371eab.gif)
